version: '2'
services:

    model_optimizer:
        build: 
            context: .
            dockerfile: ./Dockerfile
        image: openvinor3.1:latest
        user: ${CURRENT_UID}
        environment:
            - PYTHONUNBUFFERED=x
        volumes:
            - ./:/input_model
            - ./:/output_dir
        working_dir: /opt/intel/openvino/deployment_tools/model_optimizer
        entrypoint: python3 mo.py
